#!/bin/sh -xe

if [ $# -lt 1 ]
then
    echo "supply build number as the first argument"
    exit 1
fi

VERSION="0.1-$1"
TOPDIR=debian

# create deb tree
INIT_DIR=./$TOPDIR/etc/init.d
mkdir -p $INIT_DIR

# set dir mode
find ./$TOPDIR -type d | xargs chmod 755

cp ./oh-tomcat-app $INIT_DIR

# build deb package
oh-deb-build $VERSION
