#!/bin/sh -e
#
# /etc/init.d/oh-tomcat-app -- startup script for the tomcat apps
#
# generic init script for tomcat apps. this script cannot not be
# run directly. create CATALINA_BASE in /opt/{name} and then
# create sym link {name} pointing to this script, then create default
# setting (ex. JAVA_HOME, JAVA_OPTS etc.) in /etc/default/{name}

if [ `id -u` -ne 0 ]; then
    echo "You need root privileges to run this script"
    exit 1
fi

APP_NAME=$(basename "$0")
APP_LOG_DIR=/var/log/$APP_NAME
DEFAULT=/etc/default/$APP_NAME

CATALINA_HOME=/usr/share/tomcat7
CATALINA_BASE=/opt/$APP_NAME

CATALINA_TMPDIR=/tmp/tomcat7-$APP_NAME-tmp
CATALINA_OUT=$CATALINA_BASE/logs/catalina.out
CATALINA_PID="/var/run/$APP_NAME.pid"
CATALINA_SH="$CATALINA_HOME/bin/catalina.sh"

TOMCAT7_USER=tomcat7
TOMCAT7_GROUP=tomcat7

if [ -f $DEFAULT ]; then
    . "$DEFAULT"
fi

# Make sure tomcat is started with system locale
if [ -r /etc/default/locale ]; then
    . /etc/default/locale
    export LANG
fi

. /lib/lsb/init-functions

if [ -r /etc/default/rcS ]; then
    . /etc/default/rcS
fi

catalina_sh() {

    # Define the command to run Tomcat's catalina.sh as a daemon
    # set -a tells sh to export assigned variables to spawned shells.
    TOMCAT_SH="set -a; \
        source \"$DEFAULT\"; \
        cd \"$CATALINA_BASE\"; \
        JAVA_HOME=\"$JAVA_HOME\"; \
        CATALINA_HOME=\"$CATALINA_HOME\"; \
        CATALINA_BASE=\"$CATALINA_BASE\"; \
        CATALINA_OUT=\"$CATALINA_OUT\"; \
        JAVA_OPTS=\"$JAVA_OPTS\"; \
        CATALINA_PID=\"$CATALINA_PID\"; \
        CATALINA_TMPDIR=\"$CATALINA_TMPDIR\"; \
        LANG=\"$LANG\"; \
        \"$CATALINA_SH\" $@"

    # Run the catalina.sh script as a daemon
    set +e
    touch "$CATALINA_PID" "$CATALINA_OUT"
    chown $TOMCAT7_USER "$CATALINA_PID" "$CATALINA_OUT"
    start-stop-daemon --start --background --user "$TOMCAT7_USER" --group "$TOMCAT7_GROUP" \
        --chuid "$TOMCAT7_USER" --chdir "$CATALINA_TMPDIR" \
        --pidfile "$CATALINA_PID" \
        --exec /bin/bash -- -c "$TOMCAT_SH"
    status="$?"
    set +a -e
    return $status
}

case "$1" in
    start)
    if [ -z "$JAVA_HOME" ]; then
        log_failure_msg "no JDK found - please set JAVA_HOME"
        exit 1
    fi

    if [ ! -d "$CATALINA_BASE/conf" ]; then
        log_failure_msg "invalid CATALINA_BASE: $CATALINA_BASE"
        exit 1
    fi

    log_daemon_msg "Starting" "$APP_NAME"
    if start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
        --user $TOMCAT7_USER --exec "$JAVA_HOME/bin/java" \
        >/dev/null; then

        # Remove / recreate CATALINA_TMPDIR directory
        umask 022
        rm -rf "$CATALINA_TMPDIR"
        mkdir -p "$CATALINA_TMPDIR" || {
            log_failure_msg "could not create Catalina temporary directory"
            exit 1
        }
        chown $TOMCAT7_USER "$CATALINA_TMPDIR"
        chown $TOMCAT7_USER "$APP_LOG_DIR"

        catalina_sh start
        sleep 5
        if start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
            --user $TOMCAT7_USER --exec "$JAVA_HOME/bin/java" \
            >/dev/null; then
            if [ -f "$CATALINA_PID" ]; then
                rm -f "$CATALINA_PID"
            fi
            log_end_msg 1
        else
            log_end_msg 0
        fi
    else
        log_progress_msg "(already running)"
        log_end_msg 0
    fi
    ;;
    stop)
    log_daemon_msg "Stopping" "$APP_NAME"

    set +e
    if [ -f "$CATALINA_PID" ]; then
        start-stop-daemon --stop --pidfile "$CATALINA_PID" \
            --user "$TOMCAT7_USER" \
            --retry=TERM/20/KILL/5 >/dev/null
        if [ $? -eq 1 ]; then
            log_progress_msg "$APP_NAME is not running but pid file exists, cleaning up"
        elif [ $? -eq 3 ]; then
            PID="`cat $CATALINA_PID`"
            log_failure_msg "Failed to stop $APP_NAME (pid $PID)"
            exit 1
        fi
        rm -f "$CATALINA_PID"
    else
        log_progress_msg "(not running)"
    fi
    log_end_msg 0
    set -e
    ;;
    status)
    set +e
    start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
        --user $TOMCAT7_USER --exec "$JAVA_HOME/bin/java" \
        >/dev/null 2>&1
    if [ "$?" = "0" ]; then
        if [ -f "$CATALINA_PID" ]; then
            log_success_msg "$APP_NAME is not running, but pid file exists."
            exit 1
        else
            log_success_msg "$APP_NAME is not running."
            exit 3
        fi
    else
        log_success_msg "$APP_NAME is running with pid `cat $CATALINA_PID`"
    fi
    set -e
    ;;
    restart|force-reload)
    if [ -f "$CATALINA_PID" ]; then
        $0 stop
        sleep 1
    fi
    $0 start
    ;;
    try-restart)
    if start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
        --user $TOMCAT7_USER --exec "$JAVA_HOME/bin/java" \
        >/dev/null; then
        $0 start
    fi
    ;;
    *)
    log_success_msg "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0
